import Head from 'next/head'
import { Footer, Header } from '../components/common'
import Banner from '../components/Home/banner'
import Code from '../components/Home/Code'
import Authentication from '../components/Home/Authentication'
import Pricing from '../components/Home/Pricing'
import Product from '../components/Home/Product'
import Feature from '../components/Home/Feature'
import Market from '../components/Home/Market'

export default function Home() {
  return (
    <>
      <Head>
        <title>Verisys</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans&family=Montserrat&family=Open+Sans&family=Sacramento&display=swap" rel="stylesheet"></link>
      </Head>
      <main>
        <Header />
        <Banner />
        <Code />
        <Authentication />
        {/* <Pricing /> */}
        <Product />
        <Market/>
        <Feature />
        <Footer />
      </main>
    </>
  )
}
