import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { Footer, Header } from '../../components/common'

function Brand() {

  
  const fields = {
    firstname: "",
    lastname: "",
    email: "",
    organization: "",
    message: "",
}

const [formValues, setFormValues] = useState(fields)
const [formError, setFormError] = useState({})
const [isSubmit, setIsSubmit] = useState(false)

const handleChange = (e) => {
    const {name, value} = e.target
    setFormValues({ ...formValues, [name]: value })
}


const handleSubmit = (e) => {
    e.preventDefault();
    validate(formValues)
    setIsSubmit(true)
}


const validate = (values) => {
    const errors = {};
    if (!values.firstname) {
        errors.firstname = "First Name is required"
    }

    if (!values.lastname) {
        errors.lastname = "Last Name is required"
    }

    if (!values.email) {
        errors.email = "Email is required"
    }

    if (!values.organization) {
        errors.organization = "Organization Name is required"
    }
    if (!values.message) {
        errors.message = "Message Name is required"
    }
    if (Object.keys(errors).length > 0) {
      setFormError(errors)
    } else {
      console.log(formValues)
      setFormError(fields)
      setFormValues(fields)
    }
}




  return (
    <>
      <Head>
        <title>Verisys</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans&family=Montserrat&family=Open+Sans&family=Sacramento&display=swap" rel="stylesheet"></link>
      </Head>
      <main>
        <Header />
        <div>
          <div className='container'>
            <h1 className='text-[35px] font-bold text-[#0F7CC0] adjust_padding text-center brandprotection'>Brand Protection</h1>
            <div className='mt-[20px]'>
              <img className='w-[940px] flex m-auto' src="/images/brandpage.png" alt="" />
            </div>
            <p className='mt-[55px] text-[20px] text-justify font-normal capitalize brandparres'>Verisys provides anti-counterfeiting authentication technology solutions designed to protect your investment in product innovation, brand value and reputation. At the same time our solutions can create new opportunities to increase trust and engagement with consumers around the world. Our unique Holographic Fingerprint anti-counterfeit label, Check If Real mobile authentication App, and real-time data and analytics capabilities, protect physical assets from counterfeit goods. Brand and product owners receive fraud alerts if there is any potentially fraudulent activity. This groundbreaking brand protection technology from Authentic Vision enables our customers to minimize lost revenues and mitigate liability from counterfeiting activities.</p>
            <div className='mt-[70px]'>
              <img className=' bg-cover bg-center' src="/images/protection.png" alt="" />
            </div>
          </div>
          <div className="bg-[url('/images/Rectangle.png')] bg-cover mt-[70px]">
            <div className='container'>
              <div className='flex items-center justify-around protectbuild'>

                <div>
                  <h1 className='text-[35px] font-bold pt-[50px] pb-[29px] headingprotect'>Protect And Build Your Brand With Us</h1>
                  <div className='pb-[48px] btnnofprotect'>
                    <button className='bg-[#0F7CC0] text-[#FFFFFF] brandformbutton text-[25px] px-[35px] py-[12px] rounded-[10px] protectbtn'>BUILD YOUR QR CODE</button>
                  </div>
                </div>

                <div>
                  <img className='w-[446px] verisyss' src="/images/verisystext.png" alt="" />
                </div>

              </div>
            </div>
          </div>

          <div className=' mt-[70px]'>
            <div className='container relative'>
              <div className='w-[85%] flex formreswidth'>
                <div className='bg-[url("/images/samplebg.png")] '>
                  <div className='pl-[100px] w-[85%] formres'>
                    <h1 className='pt-[35px] font-extrabold text-[#FFFFFF] text-[35px] text-center formheading'>Get Free Sample Kit</h1>
                    <p className='capitalize text-[15px] text-[#FFFFFF] font-bold pt-[10px] text-center'>We are always ready to help with securing your products and brand value. If you’re ready, we would love to hear your story. You can get the conversation started by using our contact form</p>

                    <form onSubmit={handleSubmit}>
                      <div className="py-10 px-5">

                        <div className="grid grid-cols-2 gap-4">

                          <div className="col-span-2 lg:col-span-1">
                            <input type="text" className="border-solid border-gray-400 border-2 p-3 md:text-xl w-full" name='firstname' placeholder="First Name" 
                             value={formValues.firstname}
                             onChange={handleChange} />
                             <pre>{formError.firstname}</pre>
                          </div>

                          <div className="col-span-2 lg:col-span-1">
                            <input type="text" className="border-solid border-gray-400 border-2 p-3 md:text-xl w-full" name='lastname' placeholder="Last Name"
                             value={formValues.lastname}
                             onChange={handleChange} />
                             <pre>{formError.lastname}</pre>
                          </div>

                          <div className="col-span-2 lg:col-span-1">
                            <input type="text" className="border-solid border-gray-400 border-2 p-3 md:text-xl w-full" name='email' placeholder="E-mail" 
                             value={formValues.email}
                             onChange={handleChange}/>
                             <pre>{formError.email}</pre>
                          </div>

                          <div className="col-span-2 lg:col-span-1">
                            <input type="text" className="border-solid border-gray-400 border-2 p-3 md:text-xl w-full" name='organization' placeholder="Name of organization *" 
                             value={formValues.organization}
                             onChange={handleChange}/>
                             <pre>{formError.organization}</pre>
                          </div>

                          <div className="col-span-2">
                            <textarea cols="30" rows="8" className="border-solid border-gray-400 border-2 p-3 md:text-xl w-full" name='message' placeholder="Type Your Message Here........." 
                              value={formValues.message}
                              onChange={handleChange}>

                            </textarea>
                            <pre>{formError.message}</pre>
                          </div>

                          <div className="col-span-2 flex m-auto">
                            <button className="text-[25px] p-[8px] bg-[#0F7CC0] brandformbutton text-white font-bold py-[12px] px-[62px] rounded-[10px]">
                              Submit
                            </button>
                          </div>

                        </div>
                      </div>
                    </form>
                  </div>
                </div>
                <div>
                  <img className='square absolute right-[0px] h-[350px] mt-[214px]' src="/images/square.png" alt="" />
                </div>
              </div>
            </div>
          </div>

        </div>
        <Footer />
      </main>
    </>
  )
}

export default Brand
